### PR TITLE
Fix some grammar to clarify the jumbotron

### PR DESCRIPTION
**Pull request by Kadrian**
Hi! I thought the current message in the `jumbotron` section could be a little improved. Let me know what you think!

### CODE REVIEW

**Comment by php-coder** [comment]
>**HTTP response header** helps you reduce XSS risks on modern browsers by declaring with an **HTTP header** ...

It doesn't look better IMHO.

**Comment by Kadrian** [comment]
Hmm. What do you think about skipping the whole second mention of an HTTP header?

**Comment by php-coder** [comment]
> What do you think about skipping the whole second mention of an HTTP header?

Should be better.

**Comment by Kadrian** [comment]
Done :-)

**Comment by php-coder** [comment]
LGTM. If it's possible, I'd recommend to squash 2 commits into one.

@Kadrian Unfortunately, I don't have permission to merge your changes, but thank you anyway!

**Comment by pfreitag** [comment]
Looks good thanks!

**Pull request merged**
